version: "3.7"
services:
  app:
    build:
      args:
        user: laraveldocker2
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravelapache
    container_name: laravel-app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - ${LARAVEL_PORT}:80
    networks:
      - laravellist

  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
       # - ./docker-compose/config/mysql_import.cnf:/etc/mysql/conf.d/mysql_import.cnf
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravellist
  # phpmyadmin, https://hub.docker.com/r/phpmyadmin/phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9.4
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: db
      PMA_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    restart: always
    volumes:
      - ./docker-compose/config/php_upload.ini:/usr/local/etc/php/conf.d/php_upload.ini
    networks:
      - laravellist
  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravellist

networks:
  laravellist:
    driver: bridge
